/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as PartsPartIdRouteImport } from './routes/parts.$partId'
import { Route as AdminNewCategoryRouteImport } from './routes/admin.new.category'
import { Route as AdminNewMarkRouteImport } from './routes/admin.new.mark'
import { Route as AdminNewModelRouteImport } from './routes/admin.new.model'
import { Route as AdminNewPartRouteImport } from './routes/admin.new.part'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsPartIdRoute = PartsPartIdRouteImport.update({
  id: '/parts/$partId',
  path: '/parts/$partId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewCategoryRoute = AdminNewCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AdminNewRoute,
} as any)
const AdminNewMarkRoute = AdminNewMarkRouteImport.update({
  id: '/mark',
  path: '/mark',
  getParentRoute: () => AdminNewRoute,
} as any)
const AdminNewModelRoute = AdminNewModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AdminNewRoute,
} as any)
const AdminNewPartRoute = AdminNewPartRouteImport.update({
  id: '/part',
  path: '/part',
  getParentRoute: () => AdminNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contacts': typeof ContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/parts/$partId': typeof PartsPartIdRoute
  '/admin/new/category': typeof AdminNewCategoryRoute
  '/admin/new/mark': typeof AdminNewMarkRoute
  '/admin/new/model': typeof AdminNewModelRoute
  '/admin/new/part': typeof AdminNewPartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contacts': typeof ContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/parts/$partId': typeof PartsPartIdRoute
  '/admin/new/category': typeof AdminNewCategoryRoute
  '/admin/new/mark': typeof AdminNewMarkRoute
  '/admin/new/model': typeof AdminNewModelRoute
  '/admin/new/part': typeof AdminNewPartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contacts': typeof ContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/parts/$partId': typeof PartsPartIdRoute
  '/admin/new/category': typeof AdminNewCategoryRoute
  '/admin/new/mark': typeof AdminNewMarkRoute
  '/admin/new/model': typeof AdminNewModelRoute
  '/admin/new/part': typeof AdminNewPartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/contacts'
    | '/admin/login'
    | '/admin/new'
    | '/parts/$partId'
    | '/admin/new/category'
    | '/admin/new/mark'
    | '/admin/new/model'
    | '/admin/new/part'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contacts'
    | '/admin/login'
    | '/admin/new'
    | '/parts/$partId'
    | '/admin/new/category'
    | '/admin/new/mark'
    | '/admin/new/model'
    | '/admin/new/part'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/contacts'
    | '/admin/login'
    | '/admin/new'
    | '/parts/$partId'
    | '/admin/new/category'
    | '/admin/new/mark'
    | '/admin/new/model'
    | '/admin/new/part'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ContactsRoute: typeof ContactsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRouteWithChildren
  PartsPartIdRoute: typeof PartsPartIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$partId': {
      id: '/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof PartsPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new/category': {
      id: '/admin/new/category'
      path: '/category'
      fullPath: '/admin/new/category'
      preLoaderRoute: typeof AdminNewCategoryRouteImport
      parentRoute: typeof AdminNewRoute
    }
    '/admin/new/mark': {
      id: '/admin/new/mark'
      path: '/mark'
      fullPath: '/admin/new/mark'
      preLoaderRoute: typeof AdminNewMarkRouteImport
      parentRoute: typeof AdminNewRoute
    }
    '/admin/new/model': {
      id: '/admin/new/model'
      path: '/model'
      fullPath: '/admin/new/model'
      preLoaderRoute: typeof AdminNewModelRouteImport
      parentRoute: typeof AdminNewRoute
    }
    '/admin/new/part': {
      id: '/admin/new/part'
      path: '/part'
      fullPath: '/admin/new/part'
      preLoaderRoute: typeof AdminNewPartRouteImport
      parentRoute: typeof AdminNewRoute
    }
  }
}

interface AdminNewRouteChildren {
  AdminNewCategoryRoute: typeof AdminNewCategoryRoute
  AdminNewMarkRoute: typeof AdminNewMarkRoute
  AdminNewModelRoute: typeof AdminNewModelRoute
  AdminNewPartRoute: typeof AdminNewPartRoute
}

const AdminNewRouteChildren: AdminNewRouteChildren = {
  AdminNewCategoryRoute: AdminNewCategoryRoute,
  AdminNewMarkRoute: AdminNewMarkRoute,
  AdminNewModelRoute: AdminNewModelRoute,
  AdminNewPartRoute: AdminNewPartRoute,
}

const AdminNewRouteWithChildren = AdminNewRoute._addFileChildren(
  AdminNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ContactsRoute: ContactsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRouteWithChildren,
  PartsPartIdRoute: PartsPartIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
